### ISSUE TITLE
[FEATURE] 로그인 기능 개발

### ISSUE THREAD

**Issue by hellgate13** [hsquare-analytics/cancer-library#11]
### 신규 기능 개발 사항

- [ ] 사용자 로그인 기능 개발
1. 접속 방법에 따른 로그인 기능 개발
   1. 회원 가입을 통해 가입한 사용자
        - [ ] 회원 여부 확인 기능
        - [ ] 중복 접속 시 기존 세션을 삭제하는 기능
    2.  CRIS 사용자
        - [ ] CRIS 사용자 확인  기능
        - [ ] 중복 접속 시 기존 세션 삭제하는 기능

**Comment by planit-zero** [comment]
중복 접속 체크 요구사항 확인 필요
