### ISSUE TITLE
[FEATURE] 작업 생성 및 할당 기능

### ISSUE THREAD

**Issue by hellgate13** [hsquare-analytics/cancer-library#3]
### 신규 기능 개발 사항

- [ ] 작업 할당 기능
1. 검수자의 작업 할당 기능
1.1. 검수자가 작업자에게 작업 할당 기능
    - [ ] 년도 등 정의된 기준에 의한 작업 생성 기능
    - [ ] 생성한 작업에 작업자를 할당할 수 있는 기능
    - [ ] 검수 완료된 작업을 재할당할 수 있는 기능

**Comment by planit-zero** [comment]
- 할당 기준은 환자 번호로 고정
- 검수 완료된 작업을 재할당 -> 검수자가 반려
