### ISSUE TITLE
[FEATURE] 메타데이터 관리

### ISSUE THREAD

**Issue by hellgate13** [hsquare-analytics/cancer-library#8]
### 신규 기능 개발 사항

- [ ] 메타데이터 관리
- [ ] 1. 도메인(Subject) 등록 
   1. 신규 Subject을 등록하는 기능 
        - [ ] Subject 등록 기능 ( 추후 제공 )
    2.  사용하지 않는 기존 도메인을 삭제하는 기능 
        - [ ] Subject 삭제 기능 ( Activate = false ) 
    3. Category 하위의 ITEM 목록 조회
        - [ ] 하위 Topic  목록을 조회 하는 기능 

- [ ] 2. 도메인(Topic) 등록 
   1. 신규 Topic 을 등록하는 기능 
        - [ ] Topic 등록 기능 ( 추후 제공 )
    2.  사용하지 않는 기존 도메인을 삭제하는 기능 
        - [ ] Topic 삭제 기능 ( Activate = false ) 
    3. Category 하위의 Category 목록 조회
        - [ ] 하위 Categry  목록을 조회 하는 기능 

- [ ] 3. 도메인(Category) 등록 
   1. 신규 Category 을 등록하는 기능 
        - [ ] Category 등록 기능 ( 추후 제공 )
    2.  사용하지 않는 기존 도메인을 삭제하는 기능 
        - [ ] Category 삭제 기능 ( Activate = false ) 
    3. Category 하위의 Group 목록 조회
        - [ ] 하위 Group  목록을 조회 하는 기능 

- [ ] 4. 도메인(Group) 등록 
   1. 신규 Group 을 등록하는 기능 
        - [ ] Group 등록 기능 ( 추후 제공 )
    2.  사용하지 않는 기존 도메인을 삭제하는 기능 
        - [ ] Group 삭제 기능 ( Activate = false ) 
    3. Group 하위의 ITEM 목록 조회
        - [ ] 하위 Item  목록을 조회 하는 기능

- [ ] 4. 도메인(Item) 등록 
   1. 신규 Group 을 등록하는 기능 
        - [ ] Item 등록 기능 ( 추후 제공 )
    2.  사용하지 않는 기존 도메인을 삭제하는 기능 
        - [ ] Item 삭제 기능 ( Activate = false )

**Comment by hellgate13** [comment]
회의 결과 Research EX 의 메타 데이터 구조와 유사점이 있고 향후 연동을 위한 작업을 위해서 동일한 메타 데이터를 사용하기로 하여 이슈를 수정함

**Comment by hellgate13** [comment]
메타 데이터 관리 기능 이슈를 하나로 통합하여 관리하고 각 항목(Group, Category, Subject, Topic, Item) 별로 브랜치를 나눠서 작업을 진행한다.

**Comment by planit-zero** [comment]
group은 category 에 태그를 붙이는 식으로 운영가능할 듯 합니다. category(N) <-> group(N)
